# mkdocs.yml
site_name: Spark-frame

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select

plugins:
  - mkdocs-video:
      mark: "type:video-autoplay"
      is_video: True
      video_muted: True
      video_controls: True
      video_autoplay: True
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
  - search:
      lang: en
  - include-markdown:
  - mkdocstrings:
      enable_inventory: true
      default_handler: python
      handlers:
        python:
          import:
            - https://spark.apache.org/docs/latest/api/python/objects.inv
          options:
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: true
            show_source: true
            show_signature: true
            show_signature_annotations: true

extra_css:
  - css/mkdocstrings.css
  - css/custom_width.css

markdown_extensions:
  # Allows to add notes and collapsible sections etc.
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admon#usage
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - README.md
  - spark_frame

site_url: https://furcypin.github.io/spark-frame
edit_uri: https://github.com/FurcyPin/spark-frame/tree/main/docs
repo_url: https://github.com/FurcyPin/spark-frame
repo_name: FurcyPin/spark-frame

nav:
  - What is spark-frame ?: "README.md"
  - Use cases:
    - Intro: "use_cases/intro.md"
    - Comparing DataFrames: "use_cases/comparing_dataframes.md"
    - Working with nested data: "use_cases/working_with_nested_data.md"
    - Working with json: "use_cases/working_with_json.md"
    - Using flatten/unflatten: "use_cases/flatten_unflatten.md"
  - Reference:
    - spark_frame.data_diff: "reference/data_diff.md"
    - spark_frame.filesystem: "reference/filesystem.md"
    - spark_frame.functions: "reference/functions.md"
    - spark_frame.graph: "reference/graph.md"
    - spark_frame.nested: "reference/nested.md"
    - spark_frame.nested_functions: "reference/nested_functions.md"
    - spark_frame.schema_utils: "reference/schema_utils.md"
    - spark_frame.transformations: "reference/transformations.md"
