# mkdocs.yml
site_name: Spark-frame

theme:
  name: "material"

plugins:
  - search:
      lang: en
  - include-markdown:
  - mkdocstrings:
      enable_inventory: true
      default_handler: python
      handlers:
        python:
          import:
            - https://spark.apache.org/docs/latest/api/python/objects.inv
          options:
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: true
            show_source: true
            show_signature: true
            show_signature_annotations: true

extra_css:
  - css/mkdocstrings.css
  - css/custom_width.css

markdown_extensions:
  # Allows to add notes and collapsible sections etc.
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admon#usage
  - admonition
  - pymdownx.details

watch:
  - README.md
  - spark_frame

#site_url: docs/home.md
edit_uri: https://github.com/FurcyPin/spark-frame/tree/main/docs

nav:
  - What is spark-frame ?: "README.md"
  - Use cases:
    - Intro: "use_cases/intro.md"
    - Working with nested data: "use_cases/working_with_nested_data.md"
    - Working with json: "use_cases/working_with_json.md"
    - Using flatten/unflatten: "use_cases/flatten_unflatten.md"
  - Reference:
    - spark_frame.functions: "reference/functions.md"
    - spark_frame.graph: "reference/graph.md"
    - spark_frame.nested: "reference/nested.md"
    - spark_frame.nested_functions: "reference/nested_functions.md"
    - spark_frame.schema_utils: "reference/schema_utils.md"
    - spark_frame.transformations: "reference/transformations.md"
